-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.harpoon")
require("config.lldb")
require("config.rust-tools")
require("config.texlab")
require("config.tokyonight")
require("config.rust")
vim.cmd("source ~/.config/nvim/vim/vimtex.vim")
vim.cmd([[colorscheme tokyonight]])
